--liquibase formatted sql

--changeset evready-recommender:V001-create-recommendation-run-table
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'recommendation_run';
CREATE TABLE recommendation_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_json JSONB NOT NULL,
    status VARCHAR(50) NOT NULL,
    summary TEXT,
    raw_model_output TEXT,
    parsed_output_json JSONB,
    validation_status VARCHAR(50) NOT NULL,
    failure_reason TEXT,
    model_name VARCHAR(120),
    model_provider VARCHAR(80),
    temperature NUMERIC(5, 2),
    run_config_json JSONB,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE
);