--liquibase formatted sql

--changeset evready-recommender:V002-create-recommendation-candidate-snapshot-table
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'recommendation_candidate_snapshot';
CREATE TABLE recommendation_candidate_snapshot (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       recommendation_run_id BIGINT NOT NULL,
       vehicle_id BIGINT NOT NULL,
       candidate_json JSONB NOT NULL,
       rank_before_llm INTEGER,
       created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
       CONSTRAINT fk_recommendation_candidate_snapshot_run
           FOREIGN KEY (recommendation_run_id)
               REFERENCES recommendation_run (id)
               ON DELETE CASCADE
);